✨(backend) implement feature flags from .env
openfun/richie pull request #1912
Opened 2023-02-15 09:52 UTC by rlecellier

## Purpose

We need to activate / disable some features during development.
This will let us push partial features (only front,only back for example).

## Proposal

* configure feature flag in .env files with the prefix: "FEATURE_".
* add this flag in settings.py
* either use `settings.get('FEATURE_{MY_FEATURE}')` in python or use `{ feature_flags.feature 'MY_FEATURE' }` in jinja templates

## Improvement

I tried like to use a dict in .env file but i didn't find how to do it.
The idea is to set `settings.FEATURES` only once instead of editing `settings.py` each time we wanna add/remove a flag.

2023-02-16 08:02 UTC, MorganeAD requested changes
Nice job !

I think it will be nice if you add an example entry of `FEATURES` in the file https://github.com/openfun/richie/blob/master/env.d/development/dev.dist

```
# FeatureFlags
# FEATURES={"FEATURE_NAME": Bool}
FEATURES={}
```

2023-02-16 10:03 UTC, jbpenrath commented
Write some tests to ensure that feature template tag is working as expected.
e.g : https://github.com/openfun/richie/blob/master/tests/apps/courses/test_templatetags_extra_tags_is_joanie_product.py

2023-02-16 10:05 UTC, jbpenrath commented on sandbox/settings.py
> +    FEATURES = values.DictValue(environ_name="FEATURES", environ_prefix=None)
You could add default values into `dev.dist` and `dev-ssl.dist` env files. In this way by default.

2023-02-20 08:26 UTC, jbpenrath commented on src/richie/apps/core/templatetags/feature_flags.py
> +"""Custom template tags related to Joanie."""
```suggestion
"""Custom template tags related to FEATURES settings."""
```

2023-02-20 08:26 UTC, jbpenrath commented on src/richie/apps/core/templatetags/feature_flags.py
> +def features(flag):
I should catch it sooner, but by convention we try to write method whose return a boolean as a question (`is_enabled`, `has_course_runs`, ...)

What do you think to rename this template tag as follow ?
```suggestion
def is_feature_enabled(flag):
```

2023-02-20 13:24 UTC, jbpenrath approved these changes
Last few comments then merge it 👏

2023-02-20 13:24 UTC, jbpenrath commented on tests/apps/core/test_templatetags_feature_flags.py
> +    Unit test suite to validate the behavior of the joanie template tags
```suggestion
    Unit test suite to validate the behavior of the `is_feature_enabled` template tags
```

2023-02-20 13:24 UTC, jbpenrath commented on src/richie/apps/core/templatetags/feature_flags.py
> +    template tag to enable / disable features
```suggestion
    template tag to know if a feature flag is enable / disable
```

2023-02-20 13:24 UTC, jbpenrath commented on tests/apps/core/test_templatetags_feature_flags.py
> +        self.assertTrue(is_feature_enabled("TEST_FEATURE"))
Do not forgot to rename test suite and docstrings according to the new template tag name.

```suggestion
    def test_templatetags_is_feature_enabled_true(self):
        """
        `is_feature_enabled` should return True if
        an feature flags is set to True in settings.
        """
        self.assertTrue(is_feature_enabled("TEST_FEATURE"))
```

2023-02-20 13:25 UTC, jbpenrath commented on env.d/development/dev-ssl.dist
> +FEATURES = {'JOANIE_WISHLIST': True}
Missing new line

2023-02-21 09:29 UTC, MorganeAD approved these changes
:1st_place_medal:

2023-02-21 09:33 UTC, merged