✨(backend) add offer and price fields to courseRun
openfun/richie pull request #2549
Opened 2024-11-29 15:03 UTC by Tiago-Salles

## Purpose

- Add price fields to `CourseRun`
- Show price fields on the screen
- Generate json based on the [offers reference](https://developers.google.com/search/docs/appearance/structured-data/course-info#guidelines)

2024-12-13 10:50 UTC, igobranco commented
@Tiago-Salles  you should include the `price_currency` on the admin screen. For example this will be important for courses that are on different LMS platforms, for example on NAU case we have course runs on both edx.org ( use dollar) and NAU LMS (use euro).

2024-12-13 10:50 UTC, igobranco requested changes

2024-12-13 10:50 UTC, igobranco commented on src/richie/apps/courses/admin.py
> +            "certificate_price",
Add `price_currency` to the admin screen.

2024-12-13 10:50 UTC, igobranco commented on src/richie/apps/courses/admin.py
> +        "offer",
Add `price_currency` to the admin screen.

2024-12-13 11:14 UTC, igobranco commented
@Tiago-Salles  review the commit message. The `(backend) is incorrect. You have changed front and back end code.

2024-12-16 12:29 UTC, igobranco approved these changes
LGTM ✔️

2024-12-16 12:30 UTC, igobranco commented
@jbpenrath Can someone from FUN review this PR?

2025-01-29 13:56 UTC, jbpenrath approved these changes
Just some nitpicks otherwise LGTM ✅ 

Thanks for this great improvement. I'm really sorry for the delay...

2025-01-29 13:56 UTC, jbpenrath commented on src/richie/apps/courses/factories.py
> +        The offer of a course run is read from Django settings.
```suggestion
        The certificate offer of a course run is set according to its price.
```

2025-01-29 13:56 UTC, jbpenrath commented on src/richie/apps/courses/factories.py
> +        The offer of a course run is read from Django settings.
```suggestion
        The offer of a course run is set according to its price.
```

2025-02-13 11:58 UTC, Tiago-Salles commented
@jbpenrath thanks for reviewing! I have implemented your suggestions and also used the fixup commit, thanks again for sharing that. Now it seems the frontend tests on CI are failing, but they are not locally. We are encountering some difficulties with these tests, as they seem to mainly involve Jonie's business logic, and we don't have all the context to handle them. Do you have any suggestion for this, or could you confirm if this PR is ready to be merged, even with the failure on CI? Thank you!

2025-02-17 13:45 UTC, jbpenrath approved these changes

2025-02-18 10:00 UTC, merged